[window]
decorations = "None" 

[colors.bright]
black = "0x969896"
blue = "0xa0c4de"
cyan = "0xaad4cf"
green = "0xd5dda0"
magenta = "0xd2b4db"
red = "0xe68686"
white = "0xe8e8e8"
yellow = "0xf5d98c"

[colors.cursor]
cursor = "0xffffff"
text = "0x1d1f21"

[colors.normal]
black = "0x1d1f21"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xc5c8c6"
yellow = "0xf0c674"

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[font]
size = 12

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"
