#!/usr/bin/env bash

feh --bg-scale /home/rakan/.config/i3/wallpaper.jpg
sh -c '/home/rakan/.config/polybar/launch.sh'

if [ "${UMONITOR_PROFILE}" = "home" ]; then
    i3-msg "workspace number 1; move workspace to output DP-1;";
    i3-msg "workspace number 2; move workspace to output DP-1;";
    i3-msg "workspace number 3; move workspace to output DP-1;";
    i3-msg "workspace number 4; move workspace to output HDMI-2;";
    i3-msg "workspace number 5; move workspace to output HDMI-2;";
    i3-msg "workspace number 6; move workspace to output HDMI-2;";
    i3-msg "workspace number 7; move workspace to output HDMI-2;";
    i3-msg "workspace number 8; move workspace to output HDMI-2;";
    i3-msg "workspace number 9; move workspace to output HDMI-2;";
    i3-msg "workspace number 0; move workspace to output HDMI-2;";
elif [ "${UMONTITOR_PROFILE}" = "work" ]; then
    i3-msg "workspace number 1; move workspace to output HDMI-2;";
    i3-msg "workspace number 2; move workspace to output DP-1;";
    i3-msg "workspace number 3; move workspace to output HDMI-2;";
    i3-msg "workspace number 4; move workspace to output DP-1;";
    i3-msg "workspace number 5; move workspace to output DP-1;";
    i3-msg "workspace number 6; move workspace to output DP-1;";
    i3-msg "workspace number 7; move workspace to output DP-1;";
    i3-msg "workspace number 8; move workspace to output DP-1;";
    i3-msg "workspace number 9; move workspace to output DP-1;";
    i3-msg "workspace number 0; move workspace to output DP-1;";
elif [ "${UMONTITOR_PROFILE}" = "all-work" ]; then
    i3-msg "workspace number 1; move workspace to output HDMI-2;";
    i3-msg "workspace number 2; move workspace to output DP-1;";
    i3-msg "workspace number 3; move workspace to output HDMI-2;";
    i3-msg "workspace number 4; move workspace to output DP-1;";
    i3-msg "workspace number 5; move workspace to output DP-1;";
    i3-msg "workspace number 6; move workspace to output DP-1;";
    i3-msg "workspace number 7; move workspace to output eDPI-1;";
    i3-msg "workspace number 8; move workspace to output DP-1;";
    i3-msg "workspace number 9; move workspace to output DP-1;";
    i3-msg "workspace number 0; move workspace to output DP-1;";
fi
