---
media_packages:
  - vlc
  - mpv
  - ffmpeg
  - obs-studio
  - gimp
  - krita
  - gstreamer1-plugins-good
  - gstreamer1-plugins-bad-free
  - gstreamer1-plugins-bad-freeworld
  - gstreamer1-plugins-ugly
  - gstreamer1-plugin-libav
