#!/usr/bin/env sh
LOG_FILE="$HOME/.autorandr/log"
# Close STDOUT file descriptor
exec 1<&-
# Close STDERR FD
exec 2<&-

# Open STDOUT as $LOG_FILE file for read and write.
exec 1<>$LOG_FILE

# Redirect STDERR to STDOUT
exec 2>&1

# killall -q polybar
# while pgrep -x polybar >/dev/null; do sleep 1; done
unset MONITOR
/usr/bin/polybar Main &
/usr/bin/polybar HDMI &
